### ISSUE TITLE
Report EACCES spawnSync /usr/local/bin/swift-format EACCES

### ISSUE THREAD

**Issue by kayky-cas** [vknabel/vscode-apple-swift-format#11]
`Error: spawnSync /usr/local/bin/swift-format EACCES
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:602:24)
    at Object.execFileSync (child_process.js:629:15)
    at format (/home/kayky/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.1.3/out/src/SwiftFormatEditProvider.js:38:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/home/kayky/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.1.3/out/src/SwiftFormatEditProvider.js:65:16)
    at R.provideDocumentFormattingEdits (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:94:174843)
    at /home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:94:197995
    at $e._withAdapter (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:94:191442)
    at $e.$provideDocumentFormattingEdits (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:94:197973)
    at n._doInvokeHandler (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:98:13802)
    at n._invokeHandler (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:98:13486)
    at n._receiveRequest (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:98:12097)
    at n._receiveOneMessage (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:98:10826)
    at /home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:98:8922
    at l.fire (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:66:1712)
    at s.fire (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:74:15990)
    at /home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:113:30625
    at l.fire (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:66:1712)
    at s.fire (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:74:15990)
    at f._receiveMessage (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:74:21260)
    at /home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:74:18138
    at l.fire (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:66:1712)
    at w.acceptChunk (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:74:13351)
    at /home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:74:12699
    at l.fire (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:66:1712)
    at b._acceptChunk (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:113:19777)
    at /home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:113:16037
    at Socket.m (/home/kayky/.vscode-server/bin/ccbaa2d27e38e5afa3e5c21c1c7bef4657064247/out/vs/server/remoteExtensionHostProcess.js:113:13575)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by vknabel** [comment]
Hi, have you followed the installation instructions?

https://github.com/vknabel/vscode-apple-swift-format#appleswift-format-for-vs-code
