### ISSUE TITLE
Unable to format swift documents

### ISSUE THREAD

**Issue by nomo-nomad** [vknabel/vscode-apple-swift-format#12]
```
Error: Command failed: /usr/local/bin/swift-format
dyld[8447]: Library not loaded: @rpath/lib_InternalSwiftSyntaxParser.dylib
  Referenced from: /usr/local/bin/swift-format
  Reason: tried: '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/bin/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-11-11-a.xctoolchain/usr/lib/swift/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-11-11-a.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/swift/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/bin/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-11-11-a.xctoolchain/usr/lib/swift/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2021-11-11-a.xctoolchain/usr/lib/swift-5.5/macosx/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/local/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file), '/usr/lib/lib_InternalSwiftSyntaxParser.dylib' (no such file)

    at checkExecSyncError (child_process.js:633:11)
    at Object.execFileSync (child_process.js:651:15)
    at Object.func [as execFileSync] (electron/js2c/asar_bundle.js:5:1846)
    at format (/Users/nomo-nomad/.vscode-insiders/extensions/vknabel.vscode-apple-swift-format-1.1.3/out/src/SwiftFormatEditProvider.js:38:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/nomo-nomad/.vscode-insiders/extensions/vknabel.vscode-apple-swift-format-1.1.3/out/src/SwiftFormatEditProvider.js:65:16)
    at A.provideDocumentFormattingEdits (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:96007)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:119215
    at Me._withAdapter (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:112681)
    at Me.$provideDocumentFormattingEdits (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:119191)
    at t._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13790)
    at t._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:13474)
    at t._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12085)
    at t._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:10814)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:8910
    at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:34332
    at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at r.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18942)
    at n._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:23523)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21057
    at c.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at w.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15773)
    at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:14903
    at Socket.y (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:114:13813)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

Not sure if this is an issue with VSCode-Insiders or if I need to fix my swift installation, any suggestions? Can't get swift documents to format.

**Comment by vknabel** [comment]
Hi, it seems you use a development snapshot. When switching your Swift version, you also need to reinstall / recompile the correct formatter, too. 

Does this fix your issue?

**Comment by Zingam** [comment]
I also try to run the extension on linux as a spm dependency but it doesn't do anything. No error messages or I can't see any. Are instructions upto date.

I use branch "release/5.7".

**Comment by Zingam** [comment]
This is how I tried to enable SwiftLint and swift-format:

```Swift
// swift-tools-version:5.7
import PackageDescription

let package = Package(
    name: "SwiftTest",
    products: [
        .executable(name: "SwiftTest", targets: ["SwiftTest"]),
    ],
    dependencies: [
        // My dependencies
        // Dev deps
       .package(url: "https://github.com/apple/swift-format.git", branch: "release/5.7"),
       .package(url: "https://github.com/realm/SwiftLint.git", from: "0.47.1"),
    ],  
    targets: [
        .executableTarget(name: "SwiftTest"),
        .testTarget(name: "SwiftTestTests",
        dependencies: [
            .byName(name: "SwiftTest"),
        ]
        )
    ]
)
```
Then I expect Right-click format to do the trick.

I use SwiftFormat on macOS installed via brew with the extension and it works.

Now I am trying to make them work on Ubuntu via the SPM as a dependency.

**Comment by vknabel** [comment]
Hey @Zingam, I haven't tried it with swift 5.7, but released a small fix. Could you try it again? (haven't installed swift 5.7, yet)

**Comment by vknabel** [comment]
@Zingam thanks for the fast feedback. What happens if you manually run `swift run -c release swift-format --version` before opening VS Code?
It seems like just building swift-format is not sufficient on linux as it does not link the binary to `.build/release/swift-format`. At least within my docker image.

I'll install a new Ubuntu soon and have a look on Swift 5.7, too. But first I need to free some space on my disk. 😅

**Comment by Zingam** [comment]
> /home/xxx/Desktop/SwiftFormatTest/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:150:9: error: cannot find 'swiftparse_parser_set_language_version' in scope
        swiftparse_parser_set_language_version(c_parser, languageVersionCString)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/xxx/Desktop/SwiftFormatTest/.build/checkouts/swift-syntax/Sources/SwiftSyntaxParser/SyntaxParser.swift:154:7: error: cannot find 'swiftparse_parser_set_enable_bare_slash_regex_literal' in scope
      swiftparse_parser_set_enable_bare_slash_regex_literal(c_parser, enableBareSlashRegexLiteral)
      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[19/21] Compiling SwiftSyntaxParser CNodes.swift

**Comment by vknabel** [comment]
@Zingam thanks for the logs. It seems like you are unable to build Swift Format and I fear I am unable to help you until `` succeeds on your machine.

You can either open a discussion on the Swift Forums https://forums.swift.org/c/development/swift-format or an issue at the repository https://github.com/apple/swift-format/issues

What might help you is checking the branch of apple/swift-format and your Swift toolchain version. 

Meanwhile I'll have a look to fix your issue when apple/swift-format compiles.

**Comment by Zingam** [comment]
I forgot how I installed the `swift-lint` and `SwiftFormat` actually. It looks like I have compiled them from sources per your README.md as a standalone executable on Linux (on macOS I use `brew`):
`.bashrc`

```bash
# Swift

export PATH=$HOME/SDKs/Swift/swift-5.6.1-RELEASE-ubuntu20.04/usr/bin:"${PATH}"

# export PATH=$HOME/SDKs/Swift/swift-5.7-DEVELOPMENT-SNAPSHOT-2022-05-18-a-ubuntu20.04/usr/bin:"${PATH}"

export PATH=$HOME/SDKs/Swift/swift-tools/swift-format/.build/release:"${PATH}"

export PATH=$HOME/SDKs/Swift/swift-tools/SwiftLint/.build/release:"${PATH}"
```

which means I did that:

```bash
# Manually
$ git clone -b swift-5.3-branch https://github.com/apple/swift-format.git
$ swift build -c release
```

Does this command do the same:

```bash
swift run -c release swift-format --version 
```

**Comment by vknabel** [comment]
@Zingam oh I see, you picked the `swift-5.3-branch`, but you are running `swift-5.6.1`.
You need to match both:

```bash
# for swift 5.6.1
$ git clone -b swift-5.6-branch https://github.com/apple/swift-format.git
$ swift build -c release
```

See https://github.com/apple/swift-format#matching-swift-format-to-your-swift-version for more details

**Comment by Zingam** [comment]
I'm sorry for the confusion. I'm pretty sure I use the 5.6. I just copied the above snippet from the README.md

> $ swift-format --version
0.50600.1

**Comment by Zingam** [comment]
@vknabel 
`swift run -c release swift-format --version ` - It looks like that I made a noob mistake. So I got this command to work. Thank you for your help.

**Comment by vknabel** [comment]
Great to hear!
In the meantime I released a new version of this extension. Could you try again?
It might take a little while before formatting documents works properly.
This progress is visible in the lower bar (Preparing swift format)

**Comment by Zingam** [comment]
Unfortunately if I right click and select Format from the menu I get:

![image](https://user-images.githubusercontent.com/3337419/174426922-2df07293-bb24-4295-ad63-60855ad4c6ed.png)

The output was: 
```
Hello, world!
fasdfasdfasd  SDfasdfasdfasdfasd
hristo@hristo-Inspiron-15-7000-Gaming:~/Desktop/SwiftTest$ swift run -c release swift-format --version
'swifttest': warning: /home/hristo/Desktop/SwiftTest/Package.swift:11:10: warning: 'package(url:_:)' is deprecated: use specific requirement APIs instead (e.g. use 'branch:' instead of '.branch')
        .package(url: "https://github.com/apple/swift-format.git", .branch("release/5.6")),
         ^
/home/hristo/Desktop/SwiftTest/Package.swift:11:69: warning: 'branch' is deprecated
        .package(url: "https://github.com/apple/swift-format.git", .branch("release/5.6")),
                                                                    ^
Building for production...
[29/29] Linking swift-format
Build complete! (155.65s)
0.50600.1
```

OK. Some additional info:

1. I created a project:
```
mkdir SwiftTest
swift package init --type executable
```
2. Open with VSCode - waited for it to configure.
3. Type some code.
4. Tried to format it. I got the error message
5. I run in the Terminal (as seen above):

```
 swift run -c release swift-format --version
```
6. Tried: Right click format and it worked.

[SwiftTest.zip](https://github.com/vknabel/vscode-apple-swift-format/files/8933184/SwiftTest.zip)

**Comment by vknabel** [comment]
@Zingam I added some workspace settings to your project and configured a [vscode dev container](https://code.visualstudio.com/docs/remote/containers). It bundles dependencies and configurations using docker. This ensures we have nearly the same setup (only the Swift toolchain and the tooling inside the dev container is available).

[SwiftTest-with-vscode-configs.zip](https://github.com/vknabel/vscode-apple-swift-format/files/8935547/SwiftTest-with-vscode-configs.zip)

See the added `.devcontainer` and `.vscode` directories.
Currently a reload of the vscode window is required, after changing the dependencies.

As you noticed, using apple/swift-format and SwiftLint at the same time as a dependency isn't possible due to a conflict.

Formatting (or linting) is only possible after this progress has finished.
 
<img width="159" alt="Bildschirmfoto 2022-06-19 um 14 56 35" src="https://user-images.githubusercontent.com/2100336/174482715-49fe9467-c2d7-411d-9ab6-ef87db8b7cbc.png"> (<- example for SwiftLint, here: `Preparing apple/swift-format`)

As multiple extensions try to build their own dependencies in parallel which could lead to errors, try a `swift package resolve` or `swift build` before opening vscode.
