### ISSUE TITLE
Report  Command failed: /Users/xiao/Desktop/swift-format/.build/release/swift-format<unknown>: error: Unable to format <stdin>: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

### ISSUE THREAD

**Issue by yushulx** [vknabel/vscode-apple-swift-format#13]
`Error: Command failed: /Users/xiao/Desktop/swift-format/.build/release/swift-format
<unknown>: error: Unable to format <stdin>: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

    at checkExecSyncError (child_process.js:633:11)
    at Object.execFileSync (child_process.js:651:15)
    at Object.func [as execFileSync] (electron/js2c/asar_bundle.js:5:1846)
    at format (/Users/xiao/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.3/out/src/SwiftFormatEditProvider.js:38:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/xiao/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.3/out/src/SwiftFormatEditProvider.js:65:16)
    at y.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:98524)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:123086
    at be._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:116655)
    at be.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:123064)
    at n._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13812)
    at n._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:13496)
    at n._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:12107)
    at n._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:10836)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:89:8945
    at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19017)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:34267
    at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:19017)
    at s._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:23598)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:21132
    at d.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:145)
    at w.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:58:1856)
    at w.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:15848)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:66:14978
    at Socket.P (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:13790)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by vknabel** [comment]
Hi @yushulx!

Thanks for the feedback! I assume you recently updated your Swift version, but you didn’t update your formatter, right?

[apple/swift-format](https://github.com/apple/swift-format) needs to have the same version as Swift.

Does this help?

Currently there is no specialized error message, yet. But I’ll add it later.

See https://github.com/vknabel/vscode-apple-swift-format/issues/9#issuecomment-921278063

**Comment by yushulx** [comment]
@vknabel yes, you are right. I have changed the branch and rebuilt `swift-format`. It's working now. Thanks!

**Comment by vknabel** [comment]
@yushulx no problem, happy to help.
I'll keep this issue open to provide a helpful error message. 👍

**Comment by vknabel** [comment]
@yushulx the error message has been improved in [v1.1.4](https://github.com/vknabel/vscode-apple-swift-format/releases/tag/v1.1.4)
