### ISSUE TITLE
Report  Command failed: /usr/bin/env swift-formatswift-format: error while loading shared libraries: libswift_StringProcessing.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kkuehl** [vknabel/vscode-apple-swift-format#20]
`Error: Command failed: /usr/bin/env swift-format
swift-format: error while loading shared libraries: libswift_StringProcessing.so: cannot open shared object file: No such file or directory

    at checkExecSyncError (node:child_process:848:11)
    at Object.execFileSync (node:child_process:886:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:1812)
    at format (/home/user/.vscode/extensions/vknabel.vscode-apple-swift-format-1.4.0/out/src/SwiftFormatEditProvider.js:48:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/home/user/.vscode/extensions/vknabel.vscode-apple-swift-format-1.4.0/out/src/SwiftFormatEditProvider.js:75:16)
    at B.provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:39732)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:61651
    at se.s (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:56458)
    at se.$provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:96:61638)
    at u.N (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
    at u.M (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
    at u.H (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:9981)
    at u.G (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
    at d.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
    at d.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at h.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
    at c.y (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:17324)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:15795
    at d.invoke (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at w.deliver (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
    at g.fire (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
    at g.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:12045)
    at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:11332
    at Socket.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:19792)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by kkuehl** [comment]
system swift version bump i didn't notice. Nevermind :)
