### ISSUE TITLE
Report  Command failed: /usr/bin/env swift-format/usr/bin/env: 'swift-format': No such file or directory

### ISSUE THREAD

**Issue by avijeetpandey** [vknabel/vscode-apple-swift-format#22]
`Error: Command failed: /usr/bin/env swift-format
/usr/bin/env: 'swift-format': No such file or directory

	at checkExecSyncError (node:child_process:828:11)
	at Object.execFileSync (node:child_process:866:15)
	at format (/root/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.4.1/out/src/SwiftFormatEditProvider.js:48:40)
	at SwiftFormatEditProvider.provideDocumentFormattingEdits (/root/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.4.1/out/src/SwiftFormatEditProvider.js:75:16)
	at B.provideDocumentFormattingEdits (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:96:39732)
	at /vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:96:61651
	at se.s (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:96:56458)
	at se.$provideDocumentFormattingEdits (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:96:61638)
	at u.N (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:104:11208)
	at u.M (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:104:10926)
	at u.H (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:104:9981)
	at u.G (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:104:9000)
	at /vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:104:7788
	at d.invoke (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at /vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:120:15804
	at d.invoke (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at h.fire (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:14314)
	at c.y (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:17324)
	at /vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:15795
	at d.invoke (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at g.acceptChunk (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:12045)
	at /vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:11332
	at d.invoke (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
	at v.deliver (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:2029)
	at g.fire (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:63:1667)
	at g.t (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:25915)
	at g.acceptFrame (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:25721)
	at d.l (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:24386)
	at /vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:21892
	at Socket.l (/vscode/vscode-server/bin/linux-x64/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/out/vs/workbench/api/node/extensionHostProcess.js:72:19792)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.Readable.push (node:internal/streams/readable:228:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by vknabel** [comment]
Hi @avijeetpandey. Thanks for your feedback.
You need to install apple/swift-format before being able to use this extension.
See https://github.com/vknabel/vscode-apple-swift-format#global-installation

If you installed it to a different location not included in your `PATH`, set `apple-swift-format.path` accordingly.
