### ISSUE TITLE
Report EACCES spawnSync /opt/homebrew/bin EACCES

### ISSUE THREAD

**Issue by mathamer** [vknabel/vscode-apple-swift-format#28]
Happens when I try to format code in vscode.
Used to work on my older MacBook pro 2015, but now when I installed everything on brand new M2 MacBook pro it doesn't work.
I did install the extension in vscode and `brew install swift-format`, also set path to `"apple-swift-format.path": ["/opt/homebrew/bin", "swift-format"]`

`Error: spawnSync /opt/homebrew/bin EACCES
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:834:24)
    at Object.execFileSync (node:child_process:880:15)
    at Object.func [as execFileSync] (node:electron/js2c/asar_bundle:5:1812)
    at format (/Users/mhamer/.vscode/extensions/vknabel.vscode-apple-swift-format-1.4.2/out/src/SwiftFormatEditProvider.js:48:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/mhamer/.vscode/extensions/vknabel.vscode-apple-swift-format-1.4.2/out/src/SwiftFormatEditProvider.js:75:16)
    at B.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:46628)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:68809
    at ce.s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:63614)
    at ce.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:100:68796)
    at c.N (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11655)
    at c.M (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:11373)
    at c.H (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:10415)
    at c.G (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:9432)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:8220
    at E.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:16654
    at E.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:145)
    at h.deliver (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:2121)
    at n.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:63:1729)
    at p.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:72:14916)
    at MessagePortMain.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:124:14780)
    at MessagePortMain.emit (node:events:526:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:5:364)`

**Comment by vknabel** [comment]
Hi @mathamer, thanks for the report.
You need to set ``"apple-swift-format.path"` to either `"/opt/homebrew/bin/swift-format"` or `["/opt/homebrew/bin/swift-format"]`. If your `$PATH` is set up correctly, should even be able to drop the `apple-swift-format.path ` setting completely.

Setting the path to `["/opt/homebrew/bin", "swift-format"]` would result in executing `/opt/homebrew/bin` as a bash script with `swift-format` as an argument. Of course this will fail. Some use cases for this behavior would be `["swift", "run", "swift-format", "--package-path", "/path/to/the/repo"]` or `["mint", "run", "--silent", "apple/swift-format@release/5.8"]`.

**Comment by mathamer** [comment]
Thanks a lot for detailed description, it helped me out!

Replacing `["/opt/homebrew/bin", "swift-format"]` with `["/opt/homebrew/bin/swift-format"]` did the trick for me.
