### ISSUE TITLE
Report  Command failed: /usr/bin/env swift-format/usr/bin/env: ‘swift-format’: Permission denied

### ISSUE THREAD

**Issue by octavonu** [vknabel/vscode-apple-swift-format#35]
`Error: Command failed: /usr/bin/env swift-format
/usr/bin/env: ‘swift-format’: Permission denied

	at checkExecSyncError (node:child_process:904:11)
	at execFileSync (node:child_process:940:15)
	at execShellSync (/home/oonu/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.4.3/out/src/execShell.js:26:49)
	at format (/home/oonu/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.4.3/out/src/SwiftFormatEditProvider.js:48:57)
	at SwiftFormatEditProvider.provideDocumentFormattingEdits (/home/oonu/.vscode-server/extensions/vknabel.vscode-apple-swift-format-1.4.3/out/src/SwiftFormatEditProvider.js:75:16)
	at O.provideDocumentFormattingEdits (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:128:45401)
	at /home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:128:68987
	at be.s (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:128:63736)
	at be.$provideDocumentFormattingEdits (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:128:68976)
	at i.S (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:135:10827)
	at i.Q (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:135:10593)
	at i.M (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:135:9645)
	at i.L (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:135:8762)
	at s.value (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:135:7565)
	at c.z (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at g.fire (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at s.value (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:154:7902)
	at c.z (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at g.fire (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:96:14010)
	at r.z (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:96:17075)
	at s.value (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:96:15527)
	at c.z (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at s.acceptChunk (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:96:11784)
	at s.value (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:96:11071)
	at c.z (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at c.fire (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:80:2119)
	at c.z (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:19173)
	at c.acceptFrame (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:18979)
	at a.n (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:17612)
	at /home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:14959
	at Socket.f (/home/oonu/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc/out/vs/workbench/api/node/extensionHostProcess.js:151:12873)
	at Socket.emit (node:events:513:28)
	at Socket.emit (node:domain:489:12)
	at addChunk (node:internal/streams/readable:324:12)
	at readableAddChunk (node:internal/streams/readable:297:9)
	at Readable.push (node:internal/streams/readable:234:10)
	at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`

**Comment by adam-rocska** [comment]
@octavonu maybe some reprosteps? Or you don't have any either?

**Comment by octavonu** [comment]
@adam-rocska Thank you. It was my fault. I did not edit correct the .zshrc file.
