### ISSUE TITLE
Report  Command failed: /usr/local/bin/swift-format<unknown>:0:0: error: Unable to format <stdin>: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

### ISSUE THREAD

**Issue by lwi19** [vknabel/vscode-apple-swift-format#4]
`Error: Command failed: /usr/local/bin/swift-format
<unknown>:0:0: error: Unable to format <stdin>: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

	at checkExecSyncError (child_process.js:630:11)
	at Object.execFileSync (child_process.js:648:15)
	at Object.func [as execFileSync] (electron/js2c/asar.js:140:31)
	at format (/home/louis/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.1/out/src/SwiftFormatEditProvider.js:38:40)
	at SwiftFormatEditProvider.provideDocumentFormattingEdits (/home/louis/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.1/out/src/SwiftFormatEditProvider.js:65:16)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:743:615
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:208
	at new Promise (<anonymous>)
	at Object.t.asPromise (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:52:180)
	at A.provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:743:586)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:777
	at G._withAdapter (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:757:832)
	at G.$provideDocumentFormattingEdits (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:763:755)
	at g._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:926)
	at g._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:876:618)
	at g._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:875:201)
	at g._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:874:6)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:872:136
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1066:179
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at v.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:256:601)
	at t.PersistentProtocol._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:261:629)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:258:708
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:67)
	at p.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:989)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:253:341
	at Socket.t (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:263:276)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)`

**Comment by lwi19** [comment]
Hi
Here is my configuration
Linux Ubuntu 20.10
kernel 5.4.0
VScode version 1.51.1

Thank you

**Comment by lwi19** [comment]
Forgot to follow the Readme!
git clone -b swift-5.3-branch https://github.com/apple/swift-format.git
cd swift-format
swift build

It's working well
thx
