### ISSUE TITLE
Report ENOBUFS spawnSync /usr/bin/env ENOBUFS

### ISSUE THREAD

**Issue by astrocaster** [vknabel/vscode-apple-swift-format#44]
`Error: spawnSync /usr/bin/env ENOBUFS
	at Object.spawnSync (node:internal/child_process:1117:20)
	at spawnSync (node:child_process:891:24)
	at execFileSync (node:child_process:934:15)
	at func (node:electron/js2c/node_init:2:2214)
	at execShellSync (/Users/neospace/.cursor/extensions/vknabel.vscode-apple-swift-format-1.4.3/out/src/execShell.js:26:49)
	at format (/Users/neospace/.cursor/extensions/vknabel.vscode-apple-swift-format-1.4.3/out/src/SwiftFormatEditProvider.js:48:57)
	at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/neospace/.cursor/extensions/vknabel.vscode-apple-swift-format-1.4.3/out/src/SwiftFormatEditProvider.js:75:16)
	at U.provideDocumentFormattingEdits (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:100567)
	at /Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:126950
	at Le.s (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:121213)
	at Le.$provideDocumentFormattingEdits (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:162:126937)
	at h.S (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:5511)
	at h.Q (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:5277)
	at h.M (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:4323)
	at h.L (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:3440)
	at u.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:159:2227)
	at f.y (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:660)
	at f.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:877)
	at w.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14325)
	at u.value (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:185:8045)
	at f.y (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:660)
	at f.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:877)
	at w.fire (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:105:14325)
	at MessagePortMain.<anonymous> (/Applications/Cursor.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:185:6325)
	at MessagePortMain.emit (node:events:517:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)`

**Comment by vknabel** [comment]
Thanks for your report! Do you remember when this error occurred? If possible, can you link the project?
