### ISSUE TITLE
Report EACCES spawnSync /usr/local/bin/swift-format EACCES

### ISSUE THREAD

**Issue by MohamadSoufan** [vknabel/vscode-apple-swift-format#7]
`Error: spawnSync /usr/local/bin/swift-format EACCES
	at Object.spawnSync (internal/child_process.js:1067:20)
	at spawnSync (child_process.js:611:24)
	at Object.execFileSync (child_process.js:638:15)
	at Object.func [as execFileSync] (electron/js2c/asar_bundle.js:5:1846)
	at format (/Users/n1529810/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.2/out/src/SwiftFormatEditProvider.js:38:40)
	at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/n1529810/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.2/out/src/SwiftFormatEditProvider.js:65:16)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:164977
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:11884
	at new Promise (<anonymous>)
	at Object.g [as asPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:11856)
	at W.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:164948)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:187629
	at ze._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:181033)
	at ze.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:187607)
	at d._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12815)
	at d._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12507)
	at d._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11108)
	at d._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9960)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8064
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
	at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15634)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29816
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
	at E.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15634)
	at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:20892)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17778
	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1835)
	at c.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12995)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12343
	at Socket.b (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13287)
	at Socket.emit (events.js:315:20)
	at Socket.EventEmitter.emit (domain.js:467:12)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by vknabel** [comment]
Hi @MohamadSoufan, thanks for the feedback!

What happens if you run 
`/usr/local/bin/swift-format`?
Do you have swift format installed?

**Comment by MohamadSoufan** [comment]
Hey @vknabel 
Nothing happens at all 
Vscode won't format the code and pop-up to side will show up, once clicked it generates this error. 
The only swift related extension that I have is 'apple-swift-format' 
should I download other extensions?

Thanks

**Comment by vknabel** [comment]
@MohamadSoufan no you don't need an additional extension, but you need to install the "driver" as described [here](https://github.com/vknabel/vscode-apple-swift-format#global-installation).

More detailed installation instructions can be found on the formatter's repo itself: [apple/swift-format#matching-swift-format-to-your-swift-version](https://github.com/apple/swift-format#matching-swift-format-to-your-swift-version).

Thereafter you may need to adjust the target path.

Run `which swift-format` after installation on you terminal. It should return a valid path.
In my case:

```
$ which swift-format
/usr/local/bin/swift-format
```

If you have a different path, you need to add it to your VS Code settings:

```json
{
  "apple-swift-format.path": "/absolute/path/to/swift-format"
}
```

**Comment by jhoogstraat** [comment]
I am having the same issue. I build `swift-format` from source and put it in `/usr/bin` in my Dockerfile.
Now, inside my dev-container I use the root user, but the extension does not seem to be able to access the binary.

**Comment by vknabel** [comment]
@jhoogstraat could you provide me your dockerfile? Maybe I'll see the error.

**Comment by jhoogstraat** [comment]
Nevermind, the `apple-swift-format.path` was missing `/swift-format`.

The second error persists however. Maybe development is not completely in sync?
Dockerfile:
```
FROM swiftlang/swift:nightly-5.5-centos8

RUN git clone -b swift-5.5-branch https://github.com/apple/swift-format.git \
    && cd swift-format \
    && swift build -c release \
    && mv ./.build/release/swift-format /usr/bin/swift-format \
    && rm -r /swift-format
```

**Comment by vknabel** [comment]
@jhoogstraat glad you found the missing setting. 

Yes, nightlies and the branches aren’t in sync. You probably need to figure the exact version/commit out by trial and error.
