### ISSUE TITLE
Report EPIPE spawnSync /usr/local/Cellar/swift-format/0.50400.0/bin/swift-format EPIPE

### ISSUE THREAD

**Issue by Qusea** [vknabel/vscode-apple-swift-format#8]
`Error: spawnSync /usr/local/Cellar/swift-format/0.50400.0/bin/swift-format EPIPE
    at Object.spawnSync (internal/child_process.js:1067:20)
    at spawnSync (child_process.js:611:24)
    at Object.execFileSync (child_process.js:638:15)
    at Object.func [as execFileSync] (electron/js2c/asar_bundle.js:5:1846)
    at format (/Users/quseasaif/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.2/out/src/SwiftFormatEditProvider.js:38:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/quseasaif/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.2/out/src/SwiftFormatEditProvider.js:65:16)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:177113
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:12691
    at new Promise (<anonymous>)
    at Object.d [as asPromise] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:12663)
    at H.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:177084)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:199802
    at Ve._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:193249)
    at Ve.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:84:199780)
    at c._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12743)
    at c._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:12435)
    at c._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:11046)
    at c._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:9900)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:88:8004
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:29836
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at h.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:15777)
    at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:21035)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:17921
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:57:1726)
    at u.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:13138)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:65:12486
    at Socket._ (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:13107)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by vknabel** [comment]
Hi @Qusea!

Does this happen in all your projects, in a specific one or even only in a single file?

**Comment by Qusea** [comment]
> Hi @Qusea!
> 
> Does this happen in all your projects, in a specific one or even only in a single file?

It happens in every file, but I only tried it with one project.
It used to work fine, I'm not sure what changed
