### ISSUE TITLE
Report  Command failed: /usr/local/bin/swift-format<unknown>:0:0: error: Unable to format <stdin>: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

### ISSUE THREAD

**Issue by reysmerwvr** [vknabel/vscode-apple-swift-format#9]
`Error: Command failed: /usr/local/bin/swift-format
<unknown>:0:0: error: Unable to format <stdin>: The loaded '_InternalSwiftSyntaxParser' library is from a toolchain that is not compatible with this version of SwiftSyntax

    at checkExecSyncError (child_process.js:625:11)
    at Object.execFileSync (child_process.js:643:15)
    at Object.func [as execFileSync] (electron/js2c/asar_bundle.js:5:1846)
    at format (/Users/reysmervalle/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.2/out/src/SwiftFormatEditProvider.js:38:40)
    at SwiftFormatEditProvider.provideDocumentFormattingEdits (/Users/reysmervalle/.vscode/extensions/vknabel.vscode-apple-swift-format-1.1.2/out/src/SwiftFormatEditProvider.js:65:16)
    at b.provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170636)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:194209
    at xe._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:187656)
    at xe.$provideDocumentFormattingEdits (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:194187)
    at i._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13543)
    at i._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13227)
    at i._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:11838)
    at i._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10567)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8663
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30187
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15781)
    at r._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21051)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:17929
    at c.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
    at v.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13142)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12490
    at Socket.w (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13350)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)`

**Comment by vknabel** [comment]
Hi @reysmerwvr 

I assume you recently updated your Swift version, but you didn’t update your formatter, right?

[apple/swift-format](https://github.com/apple/swift-format) needs to have the same version as Swift.

Does this help?

**Comment by reysmerwvr** [comment]
> Hi @reysmerwvr
> 
> I assume you recently updated your Swift version, but you didn’t update your formatter, right?
> 
> [apple/swift-format](https://github.com/apple/swift-format) needs to have the same version as Swift.
> 
> Does this help?

Hi @vknabel thank you very much!

**Comment by vknabel** [comment]
FYI the error message has been improved in [v1.1.4](https://github.com/vknabel/vscode-apple-swift-format/releases/tag/v1.1.4)
